image:
  file: .gitpod.Dockerfile

ports:
  - port: 7687
    onOpen: open-preview

tasks:
  - command: go get github.com/neo4j/neo4j-go-driver/neo4j
    description: Install Neo4j Go driver
  - command: go run main.go
    description: Run Go program
